DROP TABLE IF EXISTS public."transactions";
DROP TABLE IF EXISTS public."__EFMigrationsHistory" CASCADE ;
DROP TABLE IF EXISTS public.asp_net_role_claims CASCADE ;
DROP TABLE IF EXISTS public.asp_net_roles CASCADE ;
DROP TABLE IF EXISTS public.asp_net_user_claims CASCADE ;
DROP TABLE IF EXISTS public.asp_net_user_logins CASCADE ;
DROP TABLE IF EXISTS public.asp_net_user_roles CASCADE ;
DROP TABLE IF EXISTS public.asp_net_user_tokens CASCADE ;
DROP TABLE IF EXISTS public.asp_net_users CASCADE ;
DROP INDEX IF EXISTS public."UserNameIndex";
DROP INDEX IF EXISTS public."EmailIndex";
DROP INDEX IF EXISTS public."RoleNameIndex";

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
                                                       "ProductVersion" character varying(32) NOT NULL,
                                                       CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "AspNetRoles" (
                               "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               "Name" character varying(256) NULL,
                               "NormalizedName" character varying(256) NULL,
                               "ConcurrencyStamp" text NULL,
                               CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
                               "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               "UserName" character varying(256) NULL,
                               "NormalizedUserName" character varying(256) NULL,
                               "Email" character varying(256) NULL,
                               "NormalizedEmail" character varying(256) NULL,
                               "EmailConfirmed" boolean NOT NULL,
                               "PasswordHash" text NULL,
                               "SecurityStamp" text NULL,
                               "ConcurrencyStamp" text NULL,
                               "PhoneNumber" text NULL,
                               "PhoneNumberConfirmed" boolean NOT NULL,
                               "TwoFactorEnabled" boolean NOT NULL,
                               "LockoutEnd" timestamp with time zone NULL,
                               "LockoutEnabled" boolean NOT NULL,
                               "AccessFailedCount" integer NOT NULL,
                               "FirstName" text NULL,
                               "LastName" text NULL,
                               CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Transactions" (
                                "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                "Title" text NULL,
                                "DueDate" timestamp without time zone NOT NULL,
                                "Amount" integer NOT NULL,
                                "Frequency" text NOT NULL,
                                "Direction" text NOT NULL,
                                CONSTRAINT "PK_Transactions" PRIMARY KEY ("Id")
);

INSERT INTO public.transactions (title, due_date, amount, frequency, direction)
VALUES ('zsebpénz', TO_DATE('03/03/2020', 'DD/MM/YYYY'), 20000, 'Single', 'Income'),
       ('gázszámla', TO_DATE('15/03/2020', 'DD/MM/YYYY'), 13458, 'Monthly', 'Expenditure'),
       ('fizetés', TO_DATE('01/03/2020', 'DD/MM/YYYY'), 300000, 'Monthly', 'Income'),
       ('közös költség', TO_DATE('09/03/2020', 'DD/MM/YYYY'), 28236, 'Monthly', 'Expenditure');


CREATE TABLE "AspNetRoleClaims" (
                                    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    "RoleId" integer NOT NULL,
                                    "ClaimType" text NULL,
                                    "ClaimValue" text NULL,
                                    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                                    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
                                    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    "UserId" integer NOT NULL,
                                    "ClaimType" text NULL,
                                    "ClaimValue" text NULL,
                                    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                                    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
                                    "LoginProvider" text NOT NULL,
                                    "ProviderKey" text NOT NULL,
                                    "ProviderDisplayName" text NULL,
                                    "UserId" integer NOT NULL,
                                    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                                    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
                                   "UserId" integer NOT NULL,
                                   "RoleId" integer NOT NULL,
                                   CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                                   CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
                                   CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
                                    "UserId" integer NOT NULL,
                                    "LoginProvider" text NOT NULL,
                                    "Name" text NOT NULL,
                                    "Value" text NULL,
                                    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                                    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200317141836_CreateIdentitySchema', '3.1.2');

ALTER TABLE "AspNetUserClaims" DROP CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId";

ALTER TABLE "AspNetUserLogins" DROP CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId";

ALTER TABLE "AspNetUserRoles" DROP CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId";

ALTER TABLE "AspNetUserTokens" DROP CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId";

ALTER TABLE "Transactions" DROP CONSTRAINT "PK_Transactions";

ALTER TABLE "AspNetUsers" DROP CONSTRAINT "PK_AspNetUsers";

ALTER TABLE "Transactions" RENAME TO transaction;

ALTER TABLE "AspNetUsers" RENAME TO AspNetUsers;

ALTER TABLE transaction RENAME COLUMN "Title" TO title;

ALTER TABLE transaction RENAME COLUMN "Frequency" TO frequency;

ALTER TABLE transaction RENAME COLUMN "Direction" TO direction;

ALTER TABLE transaction RENAME COLUMN "Amount" TO amount;

ALTER TABLE transaction RENAME COLUMN "Id" TO id;

ALTER TABLE transaction RENAME COLUMN "DueDate" TO due_date;

ALTER TABLE AspNetUsers RENAME COLUMN "Email" TO email;

ALTER TABLE AspNetUsers RENAME COLUMN "Id" TO id;

ALTER TABLE AspNetUsers RENAME COLUMN "LastName" TO last_name;

ALTER TABLE AspNetUsers RENAME COLUMN "FirstName" TO first_name;

ALTER TABLE transaction ALTER COLUMN title TYPE character varying(30);
ALTER TABLE transaction ALTER COLUMN title SET NOT NULL;
ALTER TABLE transaction ALTER COLUMN title DROP DEFAULT;

ALTER TABLE transaction ALTER COLUMN frequency TYPE text;
ALTER TABLE transaction ALTER COLUMN frequency SET NOT NULL;
ALTER TABLE transaction ALTER COLUMN frequency DROP DEFAULT;

ALTER TABLE transaction ALTER COLUMN direction TYPE text;
ALTER TABLE transaction ALTER COLUMN direction SET NOT NULL;
ALTER TABLE transaction ALTER COLUMN direction DROP DEFAULT;

ALTER TABLE AspNetUsers ALTER COLUMN email TYPE character varying(320);
ALTER TABLE AspNetUsers ALTER COLUMN email SET NOT NULL;
ALTER TABLE AspNetUsers ALTER COLUMN email DROP DEFAULT;

ALTER TABLE AspNetUsers ALTER COLUMN last_name TYPE character varying(20);
ALTER TABLE AspNetUsers ALTER COLUMN last_name SET NOT NULL;
ALTER TABLE AspNetUsers ALTER COLUMN last_name DROP DEFAULT;

ALTER TABLE AspNetUsers ALTER COLUMN first_name TYPE character varying(50);
ALTER TABLE AspNetUsers ALTER COLUMN first_name SET NOT NULL;
ALTER TABLE AspNetUsers ALTER COLUMN first_name DROP DEFAULT;

ALTER TABLE transaction ADD CONSTRAINT "PK_transaction" PRIMARY KEY (id);

ALTER TABLE AspNetUsers ADD CONSTRAINT "PK_user_data" PRIMARY KEY (id);

ALTER TABLE "AspNetUserClaims" ADD CONSTRAINT "FK_AspNetUserClaims_user_data_UserId" FOREIGN KEY ("UserId") REFERENCES AspNetUsers (id) ON DELETE CASCADE;

ALTER TABLE "AspNetUserLogins" ADD CONSTRAINT "FK_AspNetUserLogins_user_data_UserId" FOREIGN KEY ("UserId") REFERENCES AspNetUsers (id) ON DELETE CASCADE;

ALTER TABLE "AspNetUserRoles" ADD CONSTRAINT "FK_AspNetUserRoles_user_data_UserId" FOREIGN KEY ("UserId") REFERENCES AspNetUsers (id) ON DELETE CASCADE;

ALTER TABLE "AspNetUserTokens" ADD CONSTRAINT "FK_AspNetUserTokens_user_data_UserId" FOREIGN KEY ("UserId") REFERENCES AspNetUsers (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200318161915_CreateEntityConfig', '3.1.2');

ALTER TABLE "AspNetRoleClaims" DROP CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId";

ALTER TABLE "AspNetUserClaims" DROP CONSTRAINT "FK_AspNetUserClaims_user_data_UserId";

ALTER TABLE "AspNetUserLogins" DROP CONSTRAINT "FK_AspNetUserLogins_user_data_UserId";

ALTER TABLE "AspNetUserRoles" DROP CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId";

ALTER TABLE "AspNetUserRoles" DROP CONSTRAINT "FK_AspNetUserRoles_user_data_UserId";

ALTER TABLE "AspNetUserTokens" DROP CONSTRAINT "FK_AspNetUserTokens_user_data_UserId";

ALTER TABLE AspNetUsers DROP CONSTRAINT "PK_user_data";

ALTER TABLE "AspNetUserTokens" DROP CONSTRAINT "PK_AspNetUserTokens";

ALTER TABLE "AspNetUserRoles" DROP CONSTRAINT "PK_AspNetUserRoles";

ALTER TABLE "AspNetUserLogins" DROP CONSTRAINT "PK_AspNetUserLogins";

ALTER TABLE "AspNetUserClaims" DROP CONSTRAINT "PK_AspNetUserClaims";

ALTER TABLE "AspNetRoles" DROP CONSTRAINT "PK_AspNetRoles";

ALTER TABLE "AspNetRoleClaims" DROP CONSTRAINT "PK_AspNetRoleClaims";

ALTER TABLE AspNetUsers RENAME TO asp_net_users;

ALTER TABLE "AspNetUserTokens" RENAME TO asp_net_user_tokens;

ALTER TABLE "AspNetUserRoles" RENAME TO asp_net_user_roles;

ALTER TABLE "AspNetUserLogins" RENAME TO asp_net_user_logins;

ALTER TABLE "AspNetUserClaims" RENAME TO asp_net_user_claims;

ALTER TABLE "AspNetRoles" RENAME TO asp_net_roles;

ALTER TABLE "AspNetRoleClaims" RENAME TO asp_net_role_claims;

ALTER TABLE asp_net_users RENAME COLUMN email TO "Email";

ALTER TABLE asp_net_users RENAME COLUMN id TO "Id";

ALTER TABLE asp_net_users RENAME COLUMN last_name TO "LastName";

ALTER TABLE asp_net_users RENAME COLUMN first_name TO "FirstName";

ALTER INDEX "IX_AspNetUserRoles_RoleId" RENAME TO "IX_asp_net_user_roles_RoleId";

ALTER INDEX "IX_AspNetUserLogins_UserId" RENAME TO "IX_asp_net_user_logins_UserId";

ALTER INDEX "IX_AspNetUserClaims_UserId" RENAME TO "IX_asp_net_user_claims_UserId";

ALTER INDEX "IX_AspNetRoleClaims_RoleId" RENAME TO "IX_asp_net_role_claims_RoleId";

ALTER TABLE asp_net_users ALTER COLUMN "Email" TYPE character varying(256);
ALTER TABLE asp_net_users ALTER COLUMN "Email" DROP NOT NULL;
ALTER TABLE asp_net_users ALTER COLUMN "Email" DROP DEFAULT;

ALTER TABLE asp_net_users ALTER COLUMN "LastName" TYPE text;
ALTER TABLE asp_net_users ALTER COLUMN "LastName" DROP NOT NULL;
ALTER TABLE asp_net_users ALTER COLUMN "LastName" DROP DEFAULT;

ALTER TABLE asp_net_users ALTER COLUMN "FirstName" TYPE text;
ALTER TABLE asp_net_users ALTER COLUMN "FirstName" DROP NOT NULL;
ALTER TABLE asp_net_users ALTER COLUMN "FirstName" DROP DEFAULT;

ALTER TABLE asp_net_users ADD CONSTRAINT "PK_asp_net_users" PRIMARY KEY ("Id");

ALTER TABLE asp_net_user_tokens ADD CONSTRAINT "PK_asp_net_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");

ALTER TABLE asp_net_user_roles ADD CONSTRAINT "PK_asp_net_user_roles" PRIMARY KEY ("UserId", "RoleId");

ALTER TABLE asp_net_user_logins ADD CONSTRAINT "PK_asp_net_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey");

ALTER TABLE asp_net_user_claims ADD CONSTRAINT "PK_asp_net_user_claims" PRIMARY KEY ("Id");

ALTER TABLE asp_net_roles ADD CONSTRAINT "PK_asp_net_roles" PRIMARY KEY ("Id");

ALTER TABLE asp_net_role_claims ADD CONSTRAINT "PK_asp_net_role_claims" PRIMARY KEY ("Id");

ALTER TABLE asp_net_role_claims ADD CONSTRAINT f_k_asp_net_role_claims_asp_net_roles__role_id FOREIGN KEY ("RoleId") REFERENCES asp_net_roles ("Id") ON DELETE CASCADE;

ALTER TABLE asp_net_user_claims ADD CONSTRAINT f_k_asp_net_user_claims_asp_net_users__user_id FOREIGN KEY ("UserId") REFERENCES asp_net_users ("Id") ON DELETE CASCADE;

ALTER TABLE asp_net_user_logins ADD CONSTRAINT f_k_asp_net_user_logins_asp_net_users__user_id FOREIGN KEY ("UserId") REFERENCES asp_net_users ("Id") ON DELETE CASCADE;

ALTER TABLE asp_net_user_roles ADD CONSTRAINT f_k_asp_net_user_roles_asp_net_roles__role_id FOREIGN KEY ("RoleId") REFERENCES asp_net_roles ("Id") ON DELETE CASCADE;

ALTER TABLE asp_net_user_roles ADD CONSTRAINT f_k_asp_net_user_roles_asp_net_users__user_id FOREIGN KEY ("UserId") REFERENCES asp_net_users ("Id") ON DELETE CASCADE;

ALTER TABLE asp_net_user_tokens ADD CONSTRAINT f_k_asp_net_user_tokens_asp_net_users__user_id FOREIGN KEY ("UserId") REFERENCES asp_net_users ("Id") ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200318170148_NamingConvention', '3.1.2');

ALTER TABLE asp_net_role_claims DROP CONSTRAINT f_k_asp_net_role_claims_asp_net_roles__role_id;

ALTER TABLE asp_net_user_claims DROP CONSTRAINT f_k_asp_net_user_claims_asp_net_users__user_id;

ALTER TABLE asp_net_user_logins DROP CONSTRAINT f_k_asp_net_user_logins_asp_net_users__user_id;

ALTER TABLE asp_net_user_roles DROP CONSTRAINT f_k_asp_net_user_roles_asp_net_roles__role_id;

ALTER TABLE asp_net_user_roles DROP CONSTRAINT f_k_asp_net_user_roles_asp_net_users__user_id;

ALTER TABLE asp_net_user_tokens DROP CONSTRAINT f_k_asp_net_user_tokens_asp_net_users__user_id;

ALTER TABLE asp_net_users RENAME COLUMN "Email" TO email;

ALTER TABLE asp_net_users RENAME COLUMN "Id" TO id;

ALTER TABLE asp_net_users RENAME COLUMN "UserName" TO user_name;

ALTER TABLE asp_net_users RENAME COLUMN "TwoFactorEnabled" TO two_factor_enabled;

ALTER TABLE asp_net_users RENAME COLUMN "SecurityStamp" TO security_stamp;

ALTER TABLE asp_net_users RENAME COLUMN "PhoneNumberConfirmed" TO phone_number_confirmed;

ALTER TABLE asp_net_users RENAME COLUMN "PhoneNumber" TO phone_number;

ALTER TABLE asp_net_users RENAME COLUMN "PasswordHash" TO password_hash;

ALTER TABLE asp_net_users RENAME COLUMN "NormalizedUserName" TO normalized_user_name;

ALTER TABLE asp_net_users RENAME COLUMN "NormalizedEmail" TO normalized_email;

ALTER TABLE asp_net_users RENAME COLUMN "LockoutEnd" TO lockout_end;

ALTER TABLE asp_net_users RENAME COLUMN "LockoutEnabled" TO lockout_enabled;

ALTER TABLE asp_net_users RENAME COLUMN "LastName" TO last_name;

ALTER TABLE asp_net_users RENAME COLUMN "FirstName" TO first_name;

ALTER TABLE asp_net_users RENAME COLUMN "EmailConfirmed" TO email_confirmed;

ALTER TABLE asp_net_users RENAME COLUMN "ConcurrencyStamp" TO concurrency_stamp;

ALTER TABLE asp_net_users RENAME COLUMN "AccessFailedCount" TO access_failed_count;

ALTER TABLE asp_net_user_tokens RENAME COLUMN "Value" TO value;

ALTER TABLE asp_net_user_tokens RENAME COLUMN "Name" TO name;

ALTER TABLE asp_net_user_tokens RENAME COLUMN "LoginProvider" TO login_provider;

ALTER TABLE asp_net_user_tokens RENAME COLUMN "UserId" TO user_id;

ALTER TABLE asp_net_user_roles RENAME COLUMN "RoleId" TO role_id;

ALTER TABLE asp_net_user_roles RENAME COLUMN "UserId" TO user_id;

ALTER INDEX "IX_asp_net_user_roles_RoleId" RENAME TO "IX_asp_net_user_roles_role_id";

ALTER TABLE asp_net_user_logins RENAME COLUMN "UserId" TO user_id;

ALTER TABLE asp_net_user_logins RENAME COLUMN "ProviderDisplayName" TO provider_display_name;

ALTER TABLE asp_net_user_logins RENAME COLUMN "ProviderKey" TO provider_key;

ALTER TABLE asp_net_user_logins RENAME COLUMN "LoginProvider" TO login_provider;

ALTER INDEX "IX_asp_net_user_logins_UserId" RENAME TO "IX_asp_net_user_logins_user_id";

ALTER TABLE asp_net_user_claims RENAME COLUMN "Id" TO id;

ALTER TABLE asp_net_user_claims RENAME COLUMN "UserId" TO user_id;

ALTER TABLE asp_net_user_claims RENAME COLUMN "ClaimValue" TO claim_value;

ALTER TABLE asp_net_user_claims RENAME COLUMN "ClaimType" TO claim_type;

ALTER INDEX "IX_asp_net_user_claims_UserId" RENAME TO "IX_asp_net_user_claims_user_id";

ALTER TABLE asp_net_roles RENAME COLUMN "Name" TO name;

ALTER TABLE asp_net_roles RENAME COLUMN "Id" TO id;

ALTER TABLE asp_net_roles RENAME COLUMN "NormalizedName" TO normalized_name;

ALTER TABLE asp_net_roles RENAME COLUMN "ConcurrencyStamp" TO concurrency_stamp;

ALTER TABLE asp_net_role_claims RENAME COLUMN "Id" TO id;

ALTER TABLE asp_net_role_claims RENAME COLUMN "RoleId" TO role_id;

ALTER TABLE asp_net_role_claims RENAME COLUMN "ClaimValue" TO claim_value;

ALTER TABLE asp_net_role_claims RENAME COLUMN "ClaimType" TO claim_type;

ALTER INDEX "IX_asp_net_role_claims_RoleId" RENAME TO "IX_asp_net_role_claims_role_id";

ALTER TABLE asp_net_role_claims ADD CONSTRAINT f_k_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE;

ALTER TABLE asp_net_user_claims ADD CONSTRAINT f_k_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;

ALTER TABLE asp_net_user_logins ADD CONSTRAINT f_k_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;

ALTER TABLE asp_net_user_roles ADD CONSTRAINT f_k_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE;

ALTER TABLE asp_net_user_roles ADD CONSTRAINT f_k_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;

ALTER TABLE asp_net_user_tokens ADD CONSTRAINT f_k_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200318171859_AddColumnNamingConvention', '3.1.2');

ALTER TABLE transaction DROP CONSTRAINT "PK_transaction";

ALTER TABLE transaction RENAME TO transactions;

ALTER TABLE transactions ALTER COLUMN title TYPE text;
ALTER TABLE transactions ALTER COLUMN title DROP NOT NULL;
ALTER TABLE transactions ALTER COLUMN title DROP DEFAULT;

ALTER TABLE transactions ALTER COLUMN frequency TYPE integer;
ALTER TABLE transactions ALTER COLUMN frequency SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN frequency DROP DEFAULT;

ALTER TABLE transactions ALTER COLUMN direction TYPE integer;
ALTER TABLE transactions ALTER COLUMN direction SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN direction DROP DEFAULT;

ALTER TABLE transactions ADD CONSTRAINT "PK_transactions" PRIMARY KEY (id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200318172751_RemoveTransactionEntityTypeConfig', '3.1.2');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200318192232_RenameTableTransactionToTransactions', '3.1.2');

ALTER TABLE transactions ALTER COLUMN title TYPE character varying(30);
ALTER TABLE transactions ALTER COLUMN title SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN title DROP DEFAULT;

ALTER TABLE transactions ALTER COLUMN frequency TYPE text;
ALTER TABLE transactions ALTER COLUMN frequency SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN frequency DROP DEFAULT;

ALTER TABLE transactions ALTER COLUMN direction TYPE text;
ALTER TABLE transactions ALTER COLUMN direction SET NOT NULL;
ALTER TABLE transactions ALTER COLUMN direction DROP DEFAULT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200318192441_RenameTableTransactionToTransactionsWithConfig', '3.1.2');

