DROP TABLE IF EXISTS public.transactions CASCADE ;
DROP TABLE IF EXISTS public."AspNetUserTokens" CASCADE;
DROP TABLE IF EXISTS public."AspNetUsers" CASCADE;
DROP TABLE IF EXISTS public."AspNetUserRoles" CASCADE;
DROP TABLE IF EXISTS public."AspNetUserLogins" CASCADE;
DROP TABLE IF EXISTS public."AspNetUserClaims" CASCADE;
DROP TABLE IF EXISTS public."AspNetRoles" CASCADE;
DROP TABLE IF EXISTS public."AspNetRoleClaims" CASCADE;
DROP TABLE IF EXISTS public."__EFMigrationsHistory" CASCADE;



CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       migrationid character varying(150) NOT NULL,
                                                       productversion character varying(32) NOT NULL,
                                                       CONSTRAINT pk___efmigrationshistory PRIMARY KEY (migrationid)
);

CREATE TABLE "AspNetRoles" (
                               id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               name character varying(256) NULL,
                               normalizedname character varying(256) NULL,
                               concurrencystamp text NULL,
                               CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE "AspNetUsers" (
                               id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                               username character varying(256) NULL,
                               normalizedusername character varying(256) NULL,
                               email character varying(256) NULL,
                               normalizedemail character varying(256) NULL,
                               emailconfirmed boolean NOT NULL,
                               passwordhash text NULL,
                               securitystamp text NULL,
                               concurrencystamp text NULL,
                               phonenumber text NULL,
                               phonenumberconfirmed boolean NOT NULL,
                               twofactorenabled boolean NOT NULL,
                               lockoutend timestamp with time zone NULL,
                               lockoutenabled boolean NOT NULL,
                               accessfailedcount integer NOT NULL,
                               firstname text NULL,
                               lastname text NULL,
                               CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE transactions (
                              id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              title character varying(30) NOT NULL,
                              due_date timestamp without time zone NOT NULL,
                              amount integer NOT NULL,
                              frequency text NOT NULL,
                              direction text NOT NULL,
                              CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE "AspNetRoleClaims" (
                                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    roleid integer NOT NULL,
                                    claimtype text NULL,
                                    claimvalue text NULL,
                                    CONSTRAINT pk_roleclaims PRIMARY KEY (id),
                                    CONSTRAINT fk_roleclaims_aspnetroles_approleid FOREIGN KEY (roleid) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
                                    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    userid integer NOT NULL,
                                    claimtype text NULL,
                                    claimvalue text NULL,
                                    CONSTRAINT pk_userclaims PRIMARY KEY (id),
                                    CONSTRAINT fk_userclaims_aspnetusers_userid FOREIGN KEY (userid) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
                                    loginprovider text NOT NULL,
                                    providerkey text NOT NULL,
                                    providerdisplayname text NULL,
                                    userid integer NOT NULL,
                                    CONSTRAINT pk_userlogins PRIMARY KEY (loginprovider, providerkey),
                                    CONSTRAINT fk_userlogins_aspnetusers_userid FOREIGN KEY (userid) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
                                   userid integer NOT NULL,
                                   roleid integer NOT NULL,
                                   CONSTRAINT pk_userroles PRIMARY KEY (userid, roleid),
                                   CONSTRAINT fk_userroles_aspnetroles_approleid FOREIGN KEY (roleid) REFERENCES "AspNetRoles" (id) ON DELETE CASCADE,
                                   CONSTRAINT fk_userroles_aspnetusers_userid FOREIGN KEY (userid) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
                                    userid integer NOT NULL,
                                    loginprovider text NOT NULL,
                                    name text NOT NULL,
                                    value text NULL,
                                    CONSTRAINT pk_usertokens PRIMARY KEY (userid, loginprovider, name),
                                    CONSTRAINT fk_usertokens_aspnetusers_userid FOREIGN KEY (userid) REFERENCES "AspNetUsers" (id) ON DELETE CASCADE
);

CREATE INDEX ix_roleclaims_roleid ON "AspNetRoleClaims" (roleid);

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" (normalizedname);

CREATE INDEX ix_userclaims_userid ON "AspNetUserClaims" (userid);

CREATE INDEX ix_userlogins_userid ON "AspNetUserLogins" (userid);

CREATE INDEX ix_userroles_roleid ON "AspNetUserRoles" (roleid);

CREATE INDEX "EmailIndex" ON "AspNetUsers" (normalizedemail);

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" (normalizedusername);

INSERT INTO "__EFMigrationsHistory" (migrationid, productversion)
VALUES ('20200319140811_InitDatabase', '3.1.2');

INSERT INTO public.transactions (title, due_date, amount, frequency, direction)
VALUES ('zsebpénz', TO_DATE('03/03/2020', 'DD/MM/YYYY'), 20000, 'Single', 'Income'),
       ('gázszámla', TO_DATE('15/03/2020', 'DD/MM/YYYY'), 13458, 'Monthly', 'Expenditure'),
       ('fizetés', TO_DATE('01/03/2020', 'DD/MM/YYYY'), 300000, 'Monthly', 'Income'),
       ('közös költség', TO_DATE('09/03/2020', 'DD/MM/YYYY'), 28236, 'Monthly', 'Expenditure');


