CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE asp_net_roles (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name character varying(256) NULL,
    normalized_name character varying(256) NULL,
    concurrency_stamp text NULL,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE asp_net_users (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_name character varying(256) NULL,
    normalized_user_name character varying(256) NULL,
    email character varying(256) NULL,
    normalized_email character varying(256) NULL,
    email_confirmed boolean NOT NULL,
    password_hash text NULL,
    security_stamp text NULL,
    concurrency_stamp text NULL,
    phone_number text NULL,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone NULL,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    first_name text NULL,
    last_name text NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE transactions (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title character varying(30) NOT NULL,
    due_date timestamp without time zone NOT NULL,
    amount integer NOT NULL,
    frequency text NOT NULL,
    direction text NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

CREATE TABLE asp_net_role_claims (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NOT NULL,
    claim_type text NULL,
    claim_value text NULL,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_claims (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id integer NOT NULL,
    claim_type text NULL,
    claim_value text NULL,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text NULL,
    user_id integer NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_roles (
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_tokens (
    user_id integer NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text NULL,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE INDEX ix_asp_net_role_claims_role_id ON asp_net_role_claims (role_id);

CREATE UNIQUE INDEX role_name_index ON asp_net_roles (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON asp_net_user_claims (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON asp_net_user_logins (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON asp_net_user_roles (role_id);

CREATE INDEX email_index ON asp_net_users (normalized_email);

CREATE UNIQUE INDEX user_name_index ON asp_net_users (normalized_user_name);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200321212943_InitialCreate', '3.1.2');

INSERT INTO public.transactions (title, due_date, amount, frequency, direction)
VALUES ('zsebpénz', TO_DATE('03/03/2020', 'DD/MM/YYYY'), 20000, 'Single', 'Income'),
       ('gázszámla', TO_DATE('15/03/2020', 'DD/MM/YYYY'), 13458, 'Monthly', 'Expenditure'),
       ('fizetés', TO_DATE('01/03/2020', 'DD/MM/YYYY'), 300000, 'Monthly', 'Income'),
       ('közös költség', TO_DATE('09/03/2020', 'DD/MM/YYYY'), 28236, 'Monthly', 'Expenditure');
